version: "2.2"

services:
  dummy_db:
      build:
        context: ./database
        dockerfile: ./Dockerfile
      image: ny2244/dummy_db
      ports:
        - "3306:3306"
      volumes:
        - ./database/db:/var/lib/mysql
        - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      container_name: dummy_db
      environment:
        MYSQL_DATABASE: sampledb
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 1234
  dummy_web:
    image: ny2244/dummy_web
    ports:
      - "3000:3000"
    container_name: dummy_web
  dummy_server:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    image: ny2244/dummy_server
    ports:
      - "5002:5002"
    container_name: dummy_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dummy_db:3306/sampledb
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_PLATFORM: mysql
    depends_on:
      - dummy_db
    links:
      - dummy_db

